feat: add `as_env` Mustache helper that transform properties to ENV_VARIABLE
rodnansol/spring-configuration-property-documenter pull request #37
Opened 2023-03-02 13:35 UTC by Allsimon

Linked to #36

This PR adds the `as_env` helper, allowing users to transform properties to their ENV_VARIABLE form: `spring.application.name` to `SPRING_APPLICATION_NAME` .

The expected usage:
```diff
-[cols="2,1,3,1,1"]
+[cols="2,1,3,1,1,3"]
|===
-|Key |Type |Description |Default value |Deprecation
+|Key |Type |Description |Default value |Deprecation |Environment variable
{{#each properties}}
|{{key}}
|{{type}}
|{{description}}
|{{defaultValue}}
|{{propertyDeprecation}}
+|{{as_env key}}
{{/each}}
```

If you want I can open another PR that will add this to the default ADOC/MARKDOWN/XML/HTML output (behind a flag ? by default ?)

2023-03-02 16:45 UTC, nandorholozsnyak commented
In my opinion it must be optional and configurable with a configuration key coming within the AbstractTemplateCustomization class.

2023-03-02 17:00 UTC, nandorholozsnyak commented
If you really would like to make the template work you must use the `fqName` attribute in the helper function, because the key alone will not be enough for the fully qualified name.

2023-03-02 17:00 UTC, nandorholozsnyak requested changes

2023-03-02 20:51 UTC, Allsimon commented on spring-configuration-property-documenter-core/src/main/java/org/rodnansol/core/generator/template/handlebars/EnvironmentVariableHelper.java
> +import static org.springframework.util.ReflectionUtils.*;
Weird, I'm on IntelliJ and also make heavy use of editorconfig on another project, not sure why it didn't work automatically 🤔

2023-03-03 17:44 UTC, nandorholozsnyak commented
Thank you, I will merge it and do some small changes on it.

2023-03-03 17:45 UTC, nandorholozsnyak commented
@all-contributors please add @Allsimon  for code

2023-03-03 18:01 UTC, nandorholozsnyak commented
I had to downgrade the Spring Boot version, because the project requires Java 11, and the pom.xml included the newest Spring Boot 3.0, so I just downgraded it to the final 2.7.8.

After that I will update the templates as well. Thank you for your contribution.

2023-03-03 18:01 UTC, closed without merging